### ISSUE TITLE
Weird broken internal link

### ISSUE THREAD

**Issue by jabl** [AaltoScienceIT/triton-docs#16]
On the page http://scicomp.aalto.fi/triton/usage/compilers.html the first link in the first paragraph is a dangling link. However, on the page http://scicomp.aalto.fi/triton/apps/python.html the same link is present (in the .rst file both point to ../apps/index) where it works just fine.

???

**Comment by rkdarst** [comment]
One had a trailing underscore, which ends up meaning "absolute HTML
link".  Without, it does some automagic to try to link to documents.

I made both explicit by doing :doc:`link text <../link/dest>` .  This
is what I have been doing lately for explicitness.  I hope it works.


On Mon, Nov 13, 2017 at 11:20:07AM +0000, Janne Blomqvist wrote:
> On the page http://scicomp.aalto.fi/triton/usage/compilers.html the first link in the first paragraph is a dangling link. However, on the page http://scicomp.aalto.fi/triton/apps/python.html the same link is present (in the .rst file both point to ../apps/index) where it works just fine.
> 
> ???

-- 
| Richard Darst   -   http://rkd.zgib.net/   -   pgp 0xBD356740
| "Ye shall know the truth and -- the truth shall make you free"

**Comment by rkdarst** [comment]
Seems to work now...
